name: Build Font

on:
  workflow_call:
    inputs:
      font_variant:
        required: true
        type: string
        default: "Default"

  workflow_dispatch:
    inputs:
      font_variant:
        description: 'Specify the font to build'
        required: true
        type: choice
        options:
          - Default
          - Iosevka
          - MPlus

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install required packages
        run: |
          sudo apt update
          sudo apt install -y ttfautohint fontforge python3-fontforge unzip curl
          sudo apt upgrade -y

      - name: Configure font variant
        run: |
          set -e
          case "${{ inputs.font_variant }}" in
            Iosevka)
              font_name="Dyve"
              font_path="Iosevka/dist/${font_name}/TTF/*[Rr]egular*"
              git clone --depth 1 https://github.com/be5invis/Iosevka.git
              ln -s "$PWD/private-build-plans.toml" "$PWD/Iosevka"
              ;;
            Default)
              font_name="Fonts"
              font_path="MyFonts/*"
              ;;
            MPlus)
              font_name="MPlus"
              mkdir -p MPlus
              curl -L https://github.com/coz-m/MPLUS_FONTS/raw/refs/heads/master/fonts/otf/MplusCodeLatin50-Regular.otf -o MPlus/MplusCodeLatin50-Regular.ttf
              curl -L https://github.com/coz-m/MPLUS_FONTS/raw/refs/heads/master/fonts/otf/MplusCodeLatin60-Regular.otf -o MPlus/MplusCodeLatin60-Regular.otf
              font_path="MPlus/*.ttf"
              ;;
            *)
              echo "Invalid font variant: ${{ inputs.font_variant }}"
              exit 1
              ;;
          esac
          echo "font_name=$font_name" >> $GITHUB_ENV
          echo "font_path=$font_path" >> $GITHUB_ENV

      - name: Download Nerd Fonts Font Patcher
        run: |
          curl -L https://github.com/ryanoasis/nerd-fonts/releases/latest/download/FontPatcher.zip -o FontPatcher.zip
          unzip FontPatcher.zip -d nerd-fonts

      - name: Build Iosevka font (if selected)
        if: inputs.font_variant == 'Iosevka'
        run: |
          cd Iosevka
          npm install
          npm run build -- ttf::$font_name
          cd ..

      - name: Patch fonts with Nerd Fonts
        run: |
          mkdir -p patched-fonts
          for font in ${font_path}; do
            echo "Patching $font"
            fontforge -script ./nerd-fonts/font-patcher \
              --complete \
              --careful \
              --progressbars \
              --outputdir "patched-fonts" \
              "$font"
          done

      - name: Upload original fonts
        uses: actions/upload-artifact@v4
        with:
          name: ${{ env.font_name }}-fonts-original
          path: ${{ inputs.font_variant == 'Iosevka' && format('Iosevka/dist/{0}', env.font_name) || env.font_name }}
          retention-days: 7

      - name: Upload patched fonts
        uses: actions/upload-artifact@v4
        with:
          name: ${{ env.font_name }}-nerd-fonts
          path: patched-fonts
          retention-days: 7
